// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GameLibrary$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GameLibrary";
  readonly sourceName: "contracts/src/GameLibrary.sol";
  readonly abi: [];
  readonly bytecode: "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220159ffe1fe3825e56639f3cd427ca17f03ec0265817a3d996affd5e5d3fee4dc964736f6c63430008180033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f80fdfea2646970667358221220159ffe1fe3825e56639f3cd427ca17f03ec0265817a3d996affd5e5d3fee4dc964736f6c63430008180033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/src/GameLibrary.sol";
  readonly buildInfoId: "solc-0_8_24-e7605c23ac8969a9884f291f9ed470b39e331166";
}

import 'hardhat/types/artifacts';
declare module 'hardhat/types/artifacts' {
  interface ArtifactMap {
    ['GameLibrary']: GameLibrary$Type;
    ['contracts/src/GameLibrary.sol:GameLibrary']: GameLibrary$Type;
  }
}
